//! # Task Domain
//!
//! Defines task-related types and the bounded task queue port.

use std::time::Duration;

use serde::{Deserialize, Serialize};

use crate::domain::agent::AgentCapability;
use crate::domain::error::Result;

/// The current state of a task.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TaskStatus {
    /// Waiting in the queue.
    Pending,
    /// Currently being executed by an agent.
    Running,
    /// Completed successfully.
    Completed,
    /// Failed after all retries.
    Failed,
    /// Cancelled by the orchestrator or user.
    Cancelled,
}

/// A subtask generated by the planner.
///
/// Each subtask targets a specific capability and is dispatched
/// to a matching agent by the router.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubTask {
    /// Unique subtask identifier.
    pub id: String,
    /// Parent request ID.
    pub parent_request_id: String,
    /// Human-readable description of what this subtask does.
    pub description: String,
    /// Required capability to fulfill this subtask.
    pub required_capability: AgentCapability,
    /// The prompt/input for the agent.
    pub prompt: String,
    /// Maximum tokens for this subtask's response.
    pub max_tokens: Option<u64>,
    /// Timeout for this specific subtask.
    pub timeout: Option<Duration>,
    /// Current status.
    pub status: TaskStatus,
    /// Dependencies: IDs of subtasks that must complete first.
    pub depends_on: Vec<String>,
    /// How many times this subtask has been retried.
    pub retry_count: u32,
    /// Assigned agent ID (filled by the router).
    pub assigned_agent: Option<String>,
}

/// The execution plan produced by the planner.
///
/// Contains an ordered list of subtasks with potential dependencies.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionPlan {
    /// The original request ID.
    pub request_id: String,
    /// Ordered subtasks.
    pub subtasks: Vec<SubTask>,
    /// Estimated total tokens for the plan.
    pub estimated_total_tokens: u64,
}

/// Retry policy configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RetryPolicy {
    /// Maximum number of retries.
    pub max_retries: u32,
    /// Base delay between retries.
    pub base_delay: Duration,
    /// Multiplier for exponential backoff.
    pub backoff_multiplier: f64,
    /// Maximum delay between retries.
    pub max_delay: Duration,
}

impl Default for RetryPolicy {
    fn default() -> Self {
        Self {
            max_retries: 3,
            base_delay: Duration::from_secs(1),
            backoff_multiplier: 2.0,
            max_delay: Duration::from_secs(30),
        }
    }
}

/// Timeout policy configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeoutPolicy {
    /// Default timeout for agent requests.
    pub default_timeout: Duration,
    /// Maximum allowed timeout.
    pub max_timeout: Duration,
}

impl Default for TimeoutPolicy {
    fn default() -> Self {
        Self {
            default_timeout: Duration::from_secs(120),
            max_timeout: Duration::from_secs(600),
        }
    }
}

/// Port for a bounded task queue.
///
/// Each agent worker has its own queue with backpressure.
/// When the queue is full, `enqueue` returns `OrchestratorError::QueueFull`.
///
/// # Errors
/// - `QueueFull` when capacity is reached.
/// - `Timeout` if `dequeue` times out.
#[async_trait::async_trait]
pub trait TaskQueue: Send + Sync {
    /// Enqueue a subtask. Returns error if the queue is full.
    async fn enqueue(&self, task: SubTask) -> Result<()>;

    /// Dequeue the next subtask, waiting up to `timeout`.
    /// Returns `None` if the timeout elapses.
    async fn dequeue(&self, timeout: Duration) -> Result<Option<SubTask>>;

    /// Current number of pending tasks.
    async fn pending_count(&self) -> Result<usize>;

    /// Queue capacity.
    fn capacity(&self) -> usize;
}
