//! Task status, subtask, and execution plan types.

use std::time::Duration;

use serde::{Deserialize, Serialize};

use crate::domain::agent::AgentCapability;

/// The current state of a task.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TaskStatus {
    Pending,
    Running,
    Completed,
    Failed,
    Cancelled,
}

/// A subtask generated by the planner.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubTask {
    pub id: String,
    pub parent_request_id: String,
    pub description: String,
    pub required_capability: AgentCapability,
    pub prompt: String,
    pub max_tokens: Option<u64>,
    pub timeout: Option<Duration>,
    pub status: TaskStatus,
    pub depends_on: Vec<String>,
    pub retry_count: u32,
    pub assigned_agent: Option<String>,
}

/// The execution plan produced by the planner.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionPlan {
    pub request_id: String,
    pub subtasks: Vec<SubTask>,
    pub estimated_total_tokens: u64,
}
